apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: petclinic-prod
resources:
  - ../../base
images:
  - name: ghcr.io/ptrmlnda/petclinic
    digest: sha256:984891892cc0fc92e0e0fa126e9b1c84adca69fe10f6c9772c0ac5b33c4cb204