apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: petclinic-prod
resources:
  - ../../base
images:
  - name: ghcr.io/ptrmlnda/petclinic
    digest: sha256:7bbcf637548298a822967c3e580879e2cadfdd31142c146517d8167cdd0f086e
