apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: petclinic-dev
resources:
  - ../../base
images:
  - name: ghcr.io/ptrmlnda/petclinic
    digest: sha256:2bd8117c78a21783c33bf04dd001f6f17787d9739f102520019ab6dad28ec49f
