apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: petclinic-dev
resources:
  - ../../base
images:
  - name: ghcr.io/ptrmlnda/petclinic
    digest: sha256:6669f00dfb64835d7560a2b6f2bc60715ac4a3750746bbae0873f629bbe548e8
